scene
vector<shared_ptr<Quadracopter> > scene::Drone
tablica dynamiczna dronow( z lista jest problem z odwolaniem do konretnego elementu)
Referenced by GetDrone.
list<shared_ptr<ObjectOfScene> > scene::SceneObject
Lista wszystkich obiektow na scenie z ktorymi jest sprawdzana kolizja.
Referenced by GetScienceObject.
scene::scene()
vector<shared_ptr<Quadracopter> >& scene::GetDrone()
Pobranie tablicy dronow.
vector <shared_ptr<Quadracopter>> tablica dronow
References Drone.
Referenced by WriteToFile, main.
list<shared_ptr<ObjectOfScene> >& scene::GetScienceObject()
Pobranie listy obiektow na scenie.
list<shared_ptr<ObjectOfScene>> lista obiektow na scenie
References SceneObject.
Referenced by WriteToFile, ChangeOrientation, DoIt, main.