Quadracopter
Cuboid Quadracopter::hull
kadlub drona reprezentowany jako prostopadloscian+
Referenced by ChangeOrientation, Quadracopter, MoveSymetry, GetHull.
HexPrism Quadracopter::disc[kNumberOfDisc][kNumberOfDisc]
smigla drona reprezentowane przez graniastoslup szeciokatny
Referenced by ChangeOrientation, Quadracopter, MoveSymetry.
double Quadracopter::RotationAngle
sumaryczny kat obrotu
Referenced by Quadracopter, GetAngle.
double Quadracopter::radius
Promien walca przyblizajacego dron.
Referenced by Quadracopter, GetRadius.
double Quadracopter::height
polowa dlugosci walca przyblizajacego dron
Referenced by Quadracopter, IfCollision, GetHeight.
list<Vector3D> Quadracopter::track
Sciezka/Trasa jako lista punktow.
Referenced by Quadracopter, MoveSymetry, GetTrack.
friend class PlantOfObstacles
void Quadracopter::ChangeOrientation(Matrix3x3 matrix, Vector3D symetry)
Zmiana kazdego wierzcholka o zadany kat obrotu.
Aby wykonac obrot dron na poczatku jest przesuwany do bazowego ukladu wspolrzednych a dopiero nastepnie dokonana jest rotacja matrix - macierz obrotu symetry - punkt symetri
References kCubNodeNumber, hull, figures3D::rotate, disc, ObjectOfScene::symetry.
Referenced by ChangeOrientation.
Quadracopter::Quadracopter()
Stworzenie drona z automatycznym przypisaniem wierzcholkow.
References RotationAngle, ObjectOfScene::symetry, radius, height, disc, hull, Cuboid::GetSymetryPoint, track.
Quadracopter::Quadracopter(double x, double y, double z)
Konstruktor parametryczny z zadanym wektorem przesuniecia.
x - wspl x y - wsp y z - wyp x
References RotationAngle, hull, disc, ObjectOfScene::symetry, Cuboid::GetSymetryPoint, radius, height, track.
Cuboid& Quadracopter::GetHull()
Pobranie kadluba z mozliwoscia zmiany.
Cuboid& - kadlub z mozliwoscia dokonywania zmian
References hull.
Referenced by ChangeOrientation, DoIt, operator<<.
Cuboid Quadracopter::GetHull() const
Pobranie kadluba bez mozliwosci dokonywania zmian.
Cuboid - kadlub
References hull.
HexPrism& Quadracopter::operator[](int Index)
Pobranie smigiel z mozliowscia modyfikacji
Index - wybor smigla HexPrism& - smiglo z mozliwoscia modyfikacji
HexPrism Quadracopter::operator[](int Index) const
Pobranie smigla bez mozliwosci modyfikacji.
Index - wybor smigla HexPrism - smiglo bez mozliwosci modyfikacji
void Quadracopter::AddAngle(int value)
zapamietanie katu obrotu
value dodany kat obrotu
Referenced by ChangeOrientation.
double Quadracopter::GetAngle() const
pobranie sumarycznego kata obrout
double- sumaryczny kat obrotu
References RotationAngle, MoveUpDown, IfCollision.
Vector3D Quadracopter::MoveUpDown(double angle) const
Wyliczenie wektora translacji.
Funkcja wymaga interakcji z uzytkownikiem, sprawdza wszelkie warunki poprawnosci. Wylicza wektor translacji na podstawie trojkata pitogarejskiego. Zaklada sie ze ruch w przod oznacz ruch o taka sama odlegosc w kierunku x i y proporcjonalna do podanej drogiVector3D - wektor translacji , wyliczony z danych podanych przez uzytkownika
Referenced by GetAngle.
bool Quadracopter::IfCollision(Vector3D PhysicalPoint, double radius) const
Sprawdzanie kolizji z dronem.
PhysicalPoint - srodek symetri drona ktory lata radius - promien drona ktory lata true - jest detekcja kolizji false - nie ma kolizji
References ObjectOfScene::symetry, height.
Referenced by GetAngle.
double& Quadracopter::GetRadius()
Pobierz promien walca.
double& - promien
References radius.
Referenced by ChangeOrientation, DoIt.
double& Quadracopter::GetHeight()
Pobierz pol wysokosci walca.
double& - pol wysokosci walca
References height, MoveSymetry.
Vector3D Quadracopter::MoveSymetry()
Zmiana wspolrzednych srodka symetri ( punktu materialnego) podczas przemieszczania/rotacji.
Vector3D
References ObjectOfScene::symetry, hull, Cuboid::GetSymetryPoint, disc, track.
Referenced by ChangeOrientation, DoIt, GetHeight.
list<Vector3D>& Quadracopter::GetTrack()
Pobranie trasy.
list<Vector3D>& - trasa (sciezka)
References track, WriteToFile, operator<<.
Referenced by ChangeOrientation.
bool Quadracopter::WriteToFile(ofstream &stream)
Zapis drona do pliku.
stream - strumien do zapisu true - udany zapis false - nieudany zapis
Referenced by GetTrack.