Obstacles
Cuboid Obstacles::cub
Przeszkody sa wizualizowane za pomoca prostopadloscianow.
Referenced by Obstacles, IfCollision, GetObstacle.
Obstacles::Obstacles()
Construct a new Obstacles object.
References ObjectOfScene::symetry, Cuboid::GetSymetryPoint.
Obstacles::Obstacles(Vector3D centre, Vector3D size)
Construct a new Obstacles object.
centre - srodek symetrii przeszkody size - rozmiary przeszkody
References cub, ObjectOfScene::symetry.
Cuboid Obstacles::GetObstacle()
Dobranie sie do przeszkody.
Index - numer przeszkody Cuboid - przeszkoda
References cub, IfCollision, WriteToFile, operator<<.
Referenced by operator<<.
bool Obstacles::IfCollision(Vector3D PhysicalPoint, double radius) const
Sprawdzanie kolizji z obiektami.
PhysicalPoint - srodek symetri wybranego drona radius - promien walca przyblizajacego true - detekcja kolizji false - nie ma kolizji
References cub.
Referenced by GetObstacle.
bool Obstacles::WriteToFile(ofstream &stream)
Zapis przeszkody do pliku.
stream - strumien do zapisu true - udany zapis false - nieudany zapis
Referenced by GetObstacle.