Cuboid
Cuboid::Cuboid()
Tworzymy nowy obiekt prostopadloscianu.
Automatycznie przypisujemy wierzcholki Dzieki temu uzytkownik nie musi podawac wierzcholkow, tylko operuje na gotowym obiekcie
References kCubNodeNumber, figures3D::P.
Cuboid::Cuboid(double *change)
Construct a new Cuboid object.
change - zestaw parametrow okreslajacyh ustawienia i rozmiar prostopadloscianu kolejno: x,y,z,scalex,scaley,scalez
References kCubNodeNumber, figures3D::P.
Cuboid::Cuboid(Vector3D centre, Vector3D size)
Construct a new Cuboid object.
centre - srodek symetri nowego prostopadloscianu size - rozmiary prostopadloscianu
References kCubNodeNumber, figures3D::P.
Vector3D Cuboid::GetSymetryPoint() const
Pozyskanie punktu symetrii prostopadloscianu.
Za punkt symetrii przyjeto srodek ciezkosci prostopadloscianu Funkcja to moze byc wykorzystywana do przesuwania wspolrzednych do ukladu wspolrzednych prosotpadloscianuVector3D - punkt symetrii
References figures3D::P.
Referenced by ChangeOrientation, Obstacles::Obstacles, Quadracopter::Quadracopter, Quadracopter::MoveSymetry.