PzG::GnuplotLink
std::list< FileInfo > PzG::GnuplotLink::files_information_
Lista nazw plików z danymi dla gnuplota.
Pole jest zarządcą listy nazw plików, z których są wczytywane dane dotyczące rysowania obrysu brył przez program gnuplot. Operacja ta wykonywana jest po wywołaniu polecenia. Draw.
int PzG::GnuplotLink::gnuplot_input_
Pole przechowuje deskryptor do wejścia standardowego uruchomionego programu gnuplot.
int PzG::GnuplotLink::gnuplot_output_
Pole przechowuje deskryptor do weyjścia standardowego uruchomionego programu gnuplot.
bool PzG::GnuplotLink::display_error_messages_
Decyduje czy mają być wyświetlane komunikaty o błędach, czy też nie.
Wartość tego pola decyduje o tym czy komunikaty o błędach będą wyświetlane na wyjście standardowe błędów (cerr), czy też nie. true - komunikaty będę wyświetlane, false - komunikaty nie będę wyświetlane.
DrawingMode PzG::GnuplotLink::drawing_mode_
Określa aktualny tryb rysowania.
Zawartość pola determinuje sposób rysowania, jaki zostanie wymuszony na programie gnuplot poprzez wysłanie do niego odpowiednich poleceń. Wspomniane wymuszenie jest realizowane poprzez wywołanie polecenia Draw()
float PzG::GnuplotLink::x_min_
Dolny zakres wyświetlanej skali skali dla osi OX.
Określa dolny zakres wyświetlanej skali dla osi OX.
float PzG::GnuplotLink::x_max_
Górny zakres wyświetlanej skali skali dla osi OX.
Określa górny zakres wyświetlanej skali dla osi OX.
float PzG::GnuplotLink::y_min_
Dolny zakres wyświetlanej skali skali dla osi OY.
Określa dolny zakres wyświetlanej skali dla osi OY.
float PzG::GnuplotLink::y_max_
Górny zakres wyświetlanej skali skali dla osi OY.
Określa górny zakres wyświetlanej skali dla osi OY.
float PzG::GnuplotLink::z_min_
Dolny zakres wyświetlanej skali skali dla osi OZ.
Określa dolny zakres wyświetlanej skali dla osi OZ.
float PzG::GnuplotLink::z_max_
Górny zakres wyświetlanej skali skali dla osi OZ.
Określa górny zakres wyświetlanej skali dla osi OZ.
float PzG::GnuplotLink::x_scale_
Wartość tego pola definiuje skalowanie rysunku wzdłuż osi OX (oś horyzontalna ekranu).
float PzG::GnuplotLink::z_scale_
Wartość tego pola definiuje skalowanie rysunku wzdłuż osi OZ (oś wertykalna ekranu).
float PzG::GnuplotLink::x_rotation_
Wartość tego pola definiuje rotację rysunku (zmiane punktu patrzenia) względem osi OX.
float PzG::GnuplotLink::z_rotation_
Wartość tego pola definiuje rotację rysunku (zmiane punktu patrzenia) względem osi OZ.
bool PzG::GnuplotLink::show_OX_axis_
Czy oś OX ma być widoczna.
Przechowuje informację decydującą o tym czy oś OX będzie widoczna na rysunku (true), czy też nie (false).
bool PzG::GnuplotLink::show_OY_axis_
Czy oś OY ma być widoczna.
Przechowuje informację decydującą o tym czy oś OY będzie widoczna na rysunku (true), czy też nie (false).
bool PzG::GnuplotLink::show_OZ_axis_
Czy oś OZ ma być widoczna.
Przechowuje informację decydującą o tym czy oś OZ będzie widoczna na rysunku (true), czy też nie (false).
bool PzG::GnuplotLink::AddFilesToDrawCommand(std::string &command, char const **separator)
Tworzy listę parametrów umożliwiających rysowanie dodatkowych elementów.
Metoda ta przewidziana jest jako element rozszerzenia pozwalającego w klasach pochodnych powiększyć listę rysowanych elementów. Parametr command powinien zawierać polecenie plot lub splot, do którego będzie możliwe dopisanie dalszego ciągu. command - polecenie rysowania, do którego mają być dopisane nazwy plików i odpowiednie parametry dla polecenia plot. separator - zawiera znak separatora między poszczególnymi parametrami. Jeżeli parametry listy przeszkód są generowane jako pierwsze, to zmienna ta musi być wskaźnikiem do wskaźnika na łańcuch: " ".
std::string PzG::GnuplotLink::SaveRangeSettings(char axis) const
Tworzy polecenie ustawiające zakres dla danej współrzędnej.
Tworzy polecenie dla programu gnuplot ustawiające zakres współrzędnych wybranej współrzędnej x, y lub z, dla której ma być tworzony dany rysunek. axis - zawiera znak określający współrzędną, dla której ma zostać wygenerowane polecenie ustawienia zakresu. łańcuch znaków polecenia ustawiającego żądany zakres dla wybranej współrzędnej.
std::string PzG::GnuplotLink::SaveScaleRotationSettings() const
Tworzy polecenie ustawiające punkt obserwacji.
Tworzy polecenie dla programu gnuplot ustawiajające punkt obserwacji poprzez zadanie rotacji i skali dla poszczególnych osi.
bool PzG::GnuplotLink::SendToGnuplot(const char *command)
Przesyła na wejście programu gnuplot zadany ciąg znaków. command - komunikat przeznaczony do przeslania. Musi być zainicjowane połączenie z programem gnuplot. true - jesli przeslanie polecenia zakończyło się powodzeniem, false - w przypadku przeciwnym.
bool PzG::GnuplotLink::AreErrorMessagesDisplayed() const
Udostępnia informację czy mają być wyświetlane informacje o błędach.
Udostępnia wartość pola display_error_messages_. Określa ono, czy mają być wyświetlane komunikaty o błędach na wyjście standardowe, czy też nie.
bool PzG::GnuplotLink::CreateChildProcess()
Uruchamia program gnuplot jako proces potomny.
Inicjalizuje połączenie z programem gnuplot. Realizowane jest to poprzez rozwidlenie procesu i uruchomienie jako procesu potomnego programu gnuplot. Komunikacja z programem gnuplot realizowana jest poprzez przejęcie jego wejścia i wyjścia standardowego. true - gdy połączenie z programem gnuplot zostało poprawnie zainicjalizowane lub gdy już wcześniej było zainicjalizowane. false - gdy proces inicjalizacji połączenia zakończył się niepowodzeniem.
References STDIN, STDOUT.
void PzG::GnuplotLink::ErrorMessage(const char *message) const
Wyświetla na wyjście "standard error" komunikat (przekazany jako parametr), o ile pole display_error_messages_ ma wartość true. W przypadku przeciwnym komunikat nie jest wyświetlany.
void PzG::GnuplotLink::CreateCommandPreamble(std::string &preamble) const
Tworzy preambułę poprzedzającą polecenie rysowania.
Tworzy zbiór poleceń, które ustawiają właściwy tryb rysowania oraz zakresy współrzędnych, jak też wszystkie inne parametry wynikające z przyjętego trybu rysowania.
References PzG::DM_2D, PzG::DM_3D.
void PzG::GnuplotLink::Create2DPreamble(std::string &preamble) const
Tworzy preambułę poprzedzającą polecenie rysowania w trybie 2D.
Tworzy zbiór poleceń, które ustawiają właściwy tryb rysowania oraz zakresy współrzędnych, jak też wszystkie inne parametry wynikające z trybu rysowania 2D.
void PzG::GnuplotLink::Create3DPreamble(std::string &preamble) const
Tworzy preambułę poprzedzającą polecenie rysowania w trybie 3D.
Tworzy zbiór poleceń, które ustawiają właściwy tryb rysowania oraz zakresy współrzędnych, jak też wszystkie inne parametry wynikające z trybu rysowania 3D.
void PzG::GnuplotLink::show_OX_axis(bool show)
Umożliwia lub zabrania rysowania osi OX.
Umożliwia lub zabrania rysowania osi OX na rysunku wykresu. show - decyduje o tym czy oś OX będzie rysowana (true), czy też nie (false).
bool PzG::GnuplotLink::show_OX_axis() const
Czy oś OX ma być rysowana.
Udostępnia informację czy oś OX ma być rysowana, czy też nie. true - gdy oś OX ma być rysowana, false - w przypadku przeciwnym.
void PzG::GnuplotLink::show_OY_axis(bool show)
Umożliwia lub zabrania rysowania osi OY.
Umożliwia lub zabrania rysowania osi OY na rysunku wykresu. show - decyduje o tym czy oś OY będzie rysowana (true), czy też nie (false).
bool PzG::GnuplotLink::show_OY_axis() const
Czy oś OY ma być rysowana.
Udostępnia informację czy oś OY ma być rysowana, czy też nie. true - gdy oś OY ma być rysowana, false - w przypadku przeciwnym.
void PzG::GnuplotLink::show_OZ_axis(bool show)
Umożliwia lub zabrania rysowania osi OZ.
Umożliwia lub zabrania rysowania osi OZ na rysunku wykresu. show - decyduje o tym czy oś OZ będzie rysowana (true), czy też nie (false).
bool PzG::GnuplotLink::show_OZ_axis() const
Czy oś OZ ma być rysowana.
Udostępnia informację czy oś OZ ma być rysowana, czy też nie. true - gdy oś OZ ma być rysowana, false - w przypadku przeciwnym.
float PzG::GnuplotLink::Xmin() const
Udostępnia dolną wartość zakresu skali wzdłuż osi OX.
float PzG::GnuplotLink::Xmax() const
Udostępnia górną wartość zakresu skali wzdłuż osi OX.
float PzG::GnuplotLink::Ymin() const
Udostępnia dolną wartość zakresu skali wzdłuż osi OY.
float PzG::GnuplotLink::Ymax() const
Udostępnia górną wartość zakresu skali wzdłuż osi OY.
float PzG::GnuplotLink::Zmin() const
Udostępnia dolną wartość zakresu skali wzdłuż osi OZ.
float PzG::GnuplotLink::Zmax() const
Udostępnia górną wartość zakresu skali wzdłuż osi OZ.
void PzG::GnuplotLink::SetDrawingMode(DrawingMode mode)
Zmienia tryb rysowania.
Zmienia tryb rysowania jaki zostanie wymuszony na programie gnuplot. mode - wartość parametru określa nowy tryb rysowania.
Referenced by main.
DrawingMode PzG::GnuplotLink::GetDrawingMode() const
Udostępnia aktualny tryb rysowania.
Udostępnia informację o aktualnym trybie rysowania.
void PzG::GnuplotLink::SetRangeX(float Xo, float Xn)
Ustawia zakres osi OX.
Ustawia zakres osi OX. Ogranicza to obszar, który będzie zwizualizowany przez programa gnuplot. Xo - dolna granica obszaru rysowania dla osi OX. Xn - górna granica obszaru rysowania dla osi OX.
Referenced by main.
void PzG::GnuplotLink::SetRangeY(float Yo, float Yn)
Ustawia zakres osi OY.
Ustawia zakres osi OY. Ogranicza to obszar, który będzie zwizualizowany przez programa gnuplot. Yo - dolna granica obszaru rysowania dla osi OY. Yn - górna granica obszaru rysowania dla osi OY.
Referenced by main.
void PzG::GnuplotLink::SetRangeZ(float Zo, float Zn)
Ustawia zakres osi OZ.
Ustawia zakres osi OZ. Ogranicza to obszar, który będzie zwizualizowany przez programa gnuplot. Zo - dolna granica obszaru rysowania dla osi OZ. Zn - górna granica obszaru rysowania dla osi OZ.
Referenced by main.
float PzG::GnuplotLink::ScaleX() const
Udostępnia skalę dla osi OX.
Udostępnia skalę dla osi OX dla tworzonego rysunku.
float PzG::GnuplotLink::ScaleZ() const
Udostępnia skalę dla osi OZ.
Udostępnia skalę dla osi OZ dla tworzonego rysunku.
void PzG::GnuplotLink::SetScaleX(float x_scale)
Zadaje skalę wzdłuż osi OZ.
Zadaje skalę wzdłuż osi OX dla tworzonego rysunku. x_scale - skala wzdłuż osi OX.
void PzG::GnuplotLink::SetScaleZ(float z_scale)
Zadaje skalę wzdłuż osi OZ.
Zadaje skalę wzdłuż osi OZ dla tworzonego rysunku. z_scale - skala wzdłuż osi OZ.
void PzG::GnuplotLink::SetScaleXZ(float x_scale, float z_scale)
Zadaje skalę wzdłuż osi OX i OZ.
Zadaje skalę wzdłuż osi OX i OZ dla tworzonego rysunku. x_scale - skala wzdłuż osi OX. z_scale - skala wzdłuż osi OZ.
float PzG::GnuplotLink::RotationX() const
Udostępnia wartość kąta rotacji renderowanego rysunku wokół osi OX. Zwracana wartość wyrażona jest w stopiniach.
float PzG::GnuplotLink::RotationZ() const
Udostępnia wartość kąta rotacji renderowanego rysunku wokół osi OZ. Zwracana wartość wyrażona jest w stopiniach.
void PzG::GnuplotLink::SetRotationX(float x_angle)
Ustawia rotację wokół osi OX.
Zadaje kąt rotacji wokół osi OX. Umożliwia to zmianę punktu obserwacji renderowanego rysunku. x_angle - wartość kąta rotacji. Jego wartość podawana jest w stopniach.
void PzG::GnuplotLink::SetRotationZ(float z_angle)
Ustawia rotację wokół osi OZ.
Zadaje kąt rotacji wokół osi OZ. Umożliwia to zmianę punktu obserwacji renderowanego rysunku. z_angle - wartość kąta rotacji. Jego wartość podawana jest w stopniach.
Referenced by main.
void PzG::GnuplotLink::SetRotationXZ(float x_angle, float z_angle)
Ustawia rotację wokół osi OX i OZ.
Zadaje jednocześnie kąt rotacji wokół osi OX i OZ. Umożliwia to zmianę punktu obserwacji renderowanego rysunku. x_angle - wartość kąta rotacji względem osi OX. Jego wartość podawana jest w stopniach. z_angle - wartość kąta rotacji względem osi OZ. Jego wartość podawana jest w stopniach.
References PzG::LS_CONTINUOUS.
Referenced by main.
void PzG::GnuplotLink::ShowErrorMessages(bool mode=true)
Zezwala lub zabrania wyświetlania komunikatów.
Metoda pozwala, albo też zabrania wyświetlania komunikatów o blędach. Jeżeli jakaś z operacji nie powiedzie się, to jako wynik zwracana jest wartość false. Oprócz tego metody takie moga wyświetlać komunikaty, które kierowane są na wyjście "standard error" Domyślnie przymuje się, że programista nie chce dodatkwego wyświetlania komunikatów.
bool PzG::GnuplotLink::AddFilename(const char *filename, LineStyle style=LS_CONTINUOUS, int width=1)
Dodaje nazwę pliku.
Powoduje dodanie do listy plików zawierajacych dane dla gnuplota, nowej nazwy pliku. filename - nazwa pliku z danymi dla gnuplota. style - tryb rysowania danego zbioru punktow. Może być ciągły lub jako zbiór osobnych punktów. width - szerokość rysowanego obiektu. W przypadku punktów parametr ten jest połową szerokości kwadratu reprezentującego dany punkt. true - jeżeli istnieje plik o nazwie udostępnionej poprzez parametr filename oraz jest zezwolenie na jego czytanie. Nazwa pliku zostaje dodana do listy plików z danymi dla gnuplota. false - Jeżeli nie istnieje plik o nazwie przekazanej poprzez parametr filename. Nazwa pliku zostaje dodana do listy plików z danymi dla gnuplota.
References PzG::FileExists.
Referenced by main.
bool PzG::GnuplotLink::AddDrawingFromFiles(std::string &command, char const **separator)
Tworzy listę parametrów umożliwiających rysowanie brył z plików.
Tworzy napis będący parametrami dla polecenie plot programu, gnuplot. Parametry te pozwalają na rysowanie brył, których współrzędne wierzchołków zawarte są w plikach. Nazwy tych plików muszą być wcześniej dołączone do kolejki plików poprzez zastosowanie polecenia DodajNazwe. command - dopisywana jest do niego sekwencja znaków tworzących parametry dla polecenia plot. separator - zawiera znak separatora między poszczególnymi parametrami. Jeżeli parametry listy nazw plików są generowane jako pierwsze, to zmienna ta musi być wskaźnikiem do wskaźnika na łańcuch: " ". true - jeśli lista nazw plików nie jest pusta. false - w przypadku przeciwnym. Jeżeli lista nazw plików nie jest pusta, to poprzez parametr separator zostaje udostępniony łańcuch: ", ".
References PzG::LS_CONTINUOUS.
bool PzG::GnuplotLink::IsConnectionInitialized() const
Informuje, czy połączenie z gnuplot'em jest zainicjalizowane.
Informuje, czy połączenie z programem gnuplot jest zainicjowane. true - jeśli tak, false - w przypadku przeciwnym.
bool PzG::GnuplotLink::Draw()
Jeżeli lista plików nie jest pusta, to generuje sekwencje poleceń dla programu gnuplot mająca na celu narysowanie płaszczyzn na na podstawie danych zawartych w plikach z listy.Lista plików nie powinna być pusta. Nazwy plików na niej można umieścić za pomoca metody AddName. Metoda nie wymaga wcześniejszego zainicjowania połączenia z gnuplotem. true - gdy zostają poprawnie wysłane polecenia dla gnuplota. Nie oznacza to jednak, że proces rysowania zakończył się pomyślnie. false - gdy połączenie z gnuplotem nie może zostać poprawnie zainicjalizowane lub gdy lista plików jest pusta.
Referenced by ChangeOrientation, DoIt, main.
bool PzG::GnuplotLink::DrawToFile(const char *filename)
Działa analogicznie jak metoda Draw, z tą różnicą, że rysunek robota składowany jest w pliku o nazwie przekazanej przez parametr filename. Rysunek jest zapisywany w formacie PNG.Lista plików nie powinna być pusta ponadto powinno być możliwe otwarcie do zapisu pliku o nazwie przekazanej przez parametr filename, do której dołączane jest rozszerzenie .ps . Metoda nie wymaga wcześniejszego zainicjowania połączenia z programem gnuplot. true - gdy zostają poprawnie wysłane polecenia dla gnuplota. Nie oznacza to jednak, że proces rysowania zakończył się pomyślnie. false - gdy połączenie z gnuplotem nie może zostać poprawnie zainicjalizowane lub gdy lista plików jest pusta lub też gdy nie można otworzyć pliku do zapisu.
bool PzG::GnuplotLink::Init()
Inicjalizuje połączenie z programem gnuplot.
Inicjalizuje połączenie z programem gnuplot. Realizowane jest to poprzez rozwidlenie procesu i uruchomienie jako procesu potomnego programu gnuplot. Komunikacja z programem gnuplot realizowana jest poprzez przejęcie jego wejścia i wyjścia standardowego. true - gdy połączenie z programem 0gnuplot zostało poprawnie zainicjalizowane lub gdy już wcześniej było zainicjalizowane. false - gdy proces inicjalizacji połączenia zakończył się niepowodzeniem.
Referenced by main.
void PzG::GnuplotLink::DeleteLastName()
Usuwa ostatnią nazwę pliku.
Usuwa ostatnią nazwę z listy nazw plików.
void PzG::GnuplotLink::DeleteAllNames()
Kasuje zawartość listy nazw plików.
Calkowicie kasuje zawartość listy nazw plików.
PzG::GnuplotLink::GnuplotLink()
References PzG::DM_3D.
PzG::GnuplotLink::~GnuplotLink()