figures3D
vector<Vector3D> figures3D::P
wierzcholki figury geometrycznej lub punkty nalezace do niej, mozna stworzyc dowolna ilosc wierzcholkow
Referenced by Cuboid::Cuboid, Cuboid::GetSymetryPoint, rotate, Translate, HexPrism::HexPrism, HexPrism::GetSymetryPoint, HexPrism::rotor.
Vector3D& figures3D::operator[](int Index)
Odwolanie do wierzcholka z mozliwa zmiana wartosci.
Index - indeks wierzcholka Vector3D& - zwracamy wierzcholek
Vector3D figures3D::operator[](int Index) const
Odowolanie do wierzcholka bez mozliwosci zmiany wartosci.
Index - indeks wierzcholka Vector3D - zwracamy wierzcholek
References rotate, Translate.
void figures3D::rotate(Matrix3x3 matrix)
Rotacja kazdego punktu nalezacego do figury.
matrix - macierz obrotu
References P.
Referenced by operator[], Quadracopter::ChangeOrientation.
void figures3D::Translate(Vector3D offset)
translacja kazdego punktu nalezacego do danej figury
offset -zadany wektor translacji
References P.
Referenced by operator[], DoIt.