main.cpp
const int kFilmFrame
Referenced by ChangeOrientation, main.
const char* mainbody
Referenced by WriteToFile, main.
bool WriteToFile(scene WholeScene)
Zapis danych do pliku.
quadro - dron true - udany zapis false - nieudany zapis
References mainbody, scene::GetScienceObject, scene::GetDrone.
Referenced by ChangeOrientation, DoIt, main.
void PrintMenu()
Wypisanie menu.
Referenced by main.
int CountSecondsOfFrame(Speed speed)
Policzenie sekund klatki.
speed - szybkosc ruchu int - czas trwania klatki ( dla wrazenia szykosci)
Referenced by ChangeOrientation, main.
int ChangeOrientation(PzG::GnuplotLink link, scene &WholeScene, Quadracopter &quadro)
Zmiana orientacji drona.
link - link Gnuplota WholeScene - cala scena quadro - wybrany dron ktorym latamy int - 0 - udalo sie 1- nie udalo sie
References kFilmFrame, Quadracopter::AddAngle, LoadMode, Matrix< Dimension >::Type_In, Quadracopter::GetHull, Cuboid::GetSymetryPoint, Quadracopter::ChangeOrientation, WriteToFile, PzG::GnuplotLink::Draw, scene::GetScienceObject, Quadracopter::MoveSymetry, Quadracopter::GetRadius, CountSecondsOfFrame, Quadracopter::GetTrack, ObjectOfScene::GetSymetry.
Referenced by main.
void DoIt(PzG::GnuplotLink link, scene &WholeScene, Quadracopter &quadro, Vector3D vec)
Ruch w game mode.
link - link do gnuplota WholeScene - cala scena quadro - dron ktorym latamy vec - kierunek lotu
References Fast, Quadracopter::GetHull, figures3D::Translate, WriteToFile, PzG::GnuplotLink::Draw, scene::GetScienceObject, Quadracopter::MoveSymetry, Quadracopter::GetRadius.
Referenced by main.
int main()
References PzG::GnuplotLink::AddFilename, mainbody, PzG::GnuplotLink::SetDrawingMode, PzG::DM_3D, PzG::GnuplotLink::Init, PzG::GnuplotLink::SetRangeX, PzG::GnuplotLink::SetRangeY, PzG::GnuplotLink::SetRangeZ, PzG::GnuplotLink::SetRotationZ, PlantOfObstacles::AddObject, Obstacle, Root, scene::GetScienceObject, Drone, scene::GetDrone, PrintMenu, ObjectOfScene::HowManyScene, Vector< double, 3 >::HowMany, User, WriteToFile, PzG::GnuplotLink::Draw, ChangeOrientation, kFilmFrame, LoadMode, CountSecondsOfFrame, PzG::GnuplotLink::SetRotationXZ, DoIt.